"""Initial migration with all models

Revision ID: b15d570687ff
Revises: 
Create Date: 2025-11-28 23:37:23.167826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b15d570687ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('bot_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_checkout_sessions_bot_id'), 'checkout_sessions', ['bot_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_session_id'), 'checkout_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_username'), 'checkout_sessions', ['username'], unique=False)
    op.create_table('ml_signal_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('ml_probability', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('ensemble_size', sa.Numeric(precision=3, scale=0), nullable=True),
    sa.Column('individual_models', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_signal_history_instrument'), 'ml_signal_history', ['instrument'], unique=False)
    op.create_table('red_folder_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('trial_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('oanda_account_id', sa.String(), nullable=True),
    sa.Column('oanda_api_key', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('bot_id', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('admin_action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Enum('bot', 'user', 'subscription', name='adminactiontargettype'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_action_logs_id'), 'admin_action_logs', ['id'], unique=False)
    op.create_table('broker_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_name', sa.Enum('alpaca', 'oanda', name='brokername'), nullable=False),
    sa.Column('environment', sa.Enum('live', 'demo', name='environment'), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('api_secret', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('paid', 'failed', 'refunded', name='invoicestatus'), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_model_performance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(length=30), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('predicted_direction', sa.String(length=10), nullable=False),
    sa.Column('predicted_probability', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('actual_direction', sa.String(length=10), nullable=True),
    sa.Column('actual_price_change', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['ml_signal_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_model_performance_instrument'), 'ml_model_performance', ['instrument'], unique=False)
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('last4', sa.String(), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('plan_tier', sa.Enum('basic', 'pro', 'elite', name='plantier'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'trialing', 'canceled', name='subscriptionstatus'), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'pending', name='supportticketstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_credentials_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('asset_pair', sa.String(), nullable=False),
    sa.Column('bot_status', sa.Enum('launched', 'stopped', 'error', name='botstatus'), nullable=False),
    sa.Column('docker_container_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broker_credentials_id'], ['broker_credentials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_activity_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_instance_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('open_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('pnl', sa.Numeric(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bot_instance_id'], ['bot_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_trade_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('bot_instance_id', sa.UUID(), nullable=True),
    sa.Column('instrument', sa.String(length=30), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='tradeside'), nullable=False),
    sa.Column('size', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=15, scale=8), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_instance_id'], ['bot_instances.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['ml_signal_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_trade_executions_instrument'), 'ml_trade_executions', ['instrument'], unique=False)
    op.create_table('trade_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_instance_id', sa.UUID(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='tradeside'), nullable=False),
    sa.Column('size', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_instance_id'], ['bot_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_records')
    op.drop_index(op.f('ix_ml_trade_executions_instrument'), table_name='ml_trade_executions')
    op.drop_table('ml_trade_executions')
    op.drop_table('bot_activity_snapshots')
    op.drop_table('bot_instances')
    op.drop_table('support_tickets')
    op.drop_table('subscriptions')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_ml_model_performance_instrument'), table_name='ml_model_performance')
    op.drop_table('ml_model_performance')
    op.drop_table('invoices')
    op.drop_table('broker_credentials')
    op.drop_index(op.f('ix_admin_action_logs_id'), table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trial_users')
    op.drop_table('system_settings')
    op.drop_table('red_folder_events')
    op.drop_index(op.f('ix_ml_signal_history_instrument'), table_name='ml_signal_history')
    op.drop_table('ml_signal_history')
    op.drop_index(op.f('ix_checkout_sessions_username'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_session_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_bot_id'), table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    # ### end Alembic commands ###

