"""
ML Signal History Model
Stores all ML signals generated by signal services (EUR/USD, USD/JPY, etc.)
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Numeric, DateTime, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from app.db.base_class import Base


class MLSignalHistory(Base):
    __tablename__ = "ml_signal_history"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    instrument = Column(String(30), nullable=False, index=True)  # e.g., 'EUR_USD', 'USD_JPY', 'XAU_USD', 'BTC_USD'
    direction = Column(String(10), nullable=False)   # 'BUY', 'SELL', 'NEUTRAL'
    confidence = Column(String(10), nullable=False)  # 'HIGH', 'MEDIUM', 'LOW'
    confidence_score = Column(Numeric(5, 3), nullable=True)
    ml_probability = Column(Numeric(5, 3), nullable=False)  # Probability price goes UP (0-1)
    entry_price = Column(Numeric(15, 8), nullable=False)  # Increased precision for crypto, commodities, forex
    ensemble_size = Column(Numeric(3, 0), nullable=True)  # Number of models in ensemble
    individual_models = Column(JSONB, nullable=True)  # Array of individual model predictions
    indicators = Column(JSONB, nullable=True)  # All indicator values (RSI, MACD, ATR, etc.)
    timestamp = Column(DateTime(timezone=True), nullable=False, default=datetime.utcnow)
    valid_until = Column(DateTime(timezone=True), nullable=True)  # When signal expires
    created_at = Column(DateTime(timezone=True), nullable=False, default=datetime.utcnow)

    # Relationships
    ml_trade_executions = relationship("MLTradeExecution", back_populates="signal")

    def __repr__(self):
        return f"<MLSignalHistory(id={self.id}, instrument={self.instrument}, direction={self.direction}, confidence={self.confidence})>"

